### ISSUE TITLE
[Question] Han considerado replicar este proyecto en otro País diferente a Colombia ?

### ISSUE THREAD

**Issue by nmcode** [vero4karu/desparchado#69]
Me gusta mucho la idea de desparchado.co. Creo que algo así sería genial en Buenos Aires - Argentina. Acá en Buenos Aires concurren a diario infinidad de actividades culturales (me atrevería a decir que muchos más que en Bogotá) pero la información está dispersa.

Si consideran en crear una versión de desparchado para Argentina, estaría dispuesto a colaborar con el mantemiento y empujar PR's con los diferentes data sources de Argentina.

Un abrazo y saludos.

**Comment by vero4karu** [comment]
Hola, Nicolás.

Traté crear Desparchado tan universal como sea posible para poder replicarlo fácil, pero no me alcanza tiempo ni para mantener la versión de Colombia :disappointed: porque Desparchado no tiene más colaboradores permanentes y casi todos los eventos los tengo que agregar manualmente.

* ¿Quieres desplegar el código de Desparchado en otro servidor bajo otro dominio? En este caso, creo que lo único ajuste sería agregar `django-constance` o algún otro modelo/archivo de configuración para guardar los textos específicos de Colombia (correo electrónico de contacto, textos de descripción del proyecto que mencionan Colombia, sección «Acerca de») en la base de datos.
* ¿Quieres incluir otro país (Argentina) dentro del proyecto actual?

**Comment by nmcode** [comment]
Primero que todo, mil disculpas por la demora en contestar. 
Respondiendo a tus preguntas...

**- "¿Quieres desplegar el código de Desparchado en otro servidor bajo o..."**
No soy muy amante de los forks porque a veces implican el doble de esfuerzo que el proyecto original. Los forks en la mayoría resultan útil para cuando son para rescatar proyectos abandonados, pero este no es el caso. Tampoco me interesa hacer una especie de whitelabel al proyecto actual o desplegarlo bajo otro dominio, etc.

**- "¿Quieres incluir otro país (Argentina) dentro del proyecto actua...".**

Si esto posible, sería genial. Aunque el término "desparchado" no existe en el vocabulario Argentino. Pero no importa, creo lo más importante es el contenido. A mi personalmente me interesa tener todos los eventos culturales en un solo lugar, estoy seguro que otras personas también lo valorarían sin importar el nombre del servicio.

Después le doy un vistazo al codebase y veo que se puede hacer, y cómo podría enviarte un PR.

Saludos.

**Comment by vero4karu** [comment]
De acuerdo. Hay sólo una cosa que me preocupa aquí: es el contenido. Actualmente me toma al menos 3 horas a la semana para buscar y agregar eventos para Bogotá y para programar publicaciones en redes sociales. ¿Te vas a encargar de hacer lo mismo para Argentina?

**Comment by nmcode** [comment]
Hmm No lo creo. Pero es algo que se podría automatizar de alguna manera. ¿no?

**Comment by vero4karu** [comment]
Tal vez, pero hace falta una persona que se encargue de hacer eso Argentina, junto con promocionar la plataforma allá, administrar las redes sociales y verificar los datos de eventos y espacios. Actualmente, yo tengo tiempo para hacerlo solamente para Bogotá.

Sin embargo, podemos mirar la posibilidad agregar soporte para varias países en el código, pero sin tener una persona que se comprometa a mantener la plataforma para Argentina, no veo sentido de desplegar ese cambio en producción.

**Comment by nmcode** [comment]
Yo tampoco tengo tiempo para dedicarme a administrar redes sociales. Buscaba más en realizar un aporte a nivel de programación. Pero entiendo la importancia que tiene mantener activa una comunidad en torno a los eventos y sobretodo pensando en otro País completamente diferente.

De todas formas no descarto la posibilidad de colaborar a futuro pero por ahora "cierro" el ticket.

Gracias por tu tiempo, saludos.
